### ISSUE TITLE
Problem running workflow containers

### ISSUE THREAD

**Issue by borazem** [ManageIQ/manageiq-providers-workflows#115] opened 2024-09-09 14:47 UTC
# Issue description #
When a simple container is used in workflow, the following error is seen in the `journal log` for identifier `workflows`:

`journalctl -t workflows`
```
Sep 04 17:08:23 ljlab-ocp4aiops-ia-ic.benoibm.com workflows[16666]: ERROR -- workflows: Q-task_id([r2000000000008_service_template_provision_task_2000000000008]) Running state: [Task:GetFolderName] with input [{"Result"=>"provisioned"}]...Complete workflow - output: [{"Error"=>"time=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"The cgroupv2 manager is set to systemd but there is no systemd user session available\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"For using systemd, you may need to log in using a user session\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Alternatively, you can enable lingering with: `loginctl enable-linger 988` (possibly as root)\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Falling back to --cgroup-manager=cgroupfs\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"The cgroupv2 manager is set to systemd but there is no systemd user session available\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"For using systemd, you may need to log in using a user session\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Alternatively, you can enable lingering with: `loginctl enable-linger 988` (possibly as root)\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Falling back to --cgroup-manager=cgroupfs\""}]

Sep 04 17:08:23 ljlab-ocp4aiops-ia-ic.benoibm.com workflows[16666]: ERROR -- workflows: Q-task_id([r2000000000008_service_template_provision_task_2000000000008]) Running state: [Task:GetFolderName] with input [{"Result"=>"provisioned"}]...Complete workflow - output: [{"Error"=>"time=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"The cgroupv2 manager is set to systemd but there is no systemd user session available\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"For using systemd, you may need to log in using a user session\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Alternatively, you can enable lingering with: `loginctl enable-linger 988` (possibly as root)\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Falling back to --cgroup-manager=cgroupfs\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"The cgroupv2 manager is set to systemd but there is no systemd user session available\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"For using systemd, you may need to log in using a user session\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Alternatively, you can enable lingering with: `loginctl enable-linger 988` (possibly as root)\"\ntime=\"2024-09-04T17:08:23-04:00\" level=warning msg=\"Falling back to --cgroup-manager=cgroupfs\""}]
```

In addition, the documentation here the following explanation is provided for running embedded workflows on appliance with podman:
```
# su manageiq
$ podman login docker.io
Username:
Password:
Login Succeeded!
```
However, if one would run any command in the manageiq user context the following error will be returned:
```
[root@ljlab-ocp4aiops-ia-ic ~]# su manageiq
[manageiq@ljlab-ocp4aiops-ia-ic root]$ podman images
ERRO[0000] mkdir /run/user/0/libpod: permission denied  
```
or similarly:
```
[root@ljlab-ocp4aiops-ia-ic ~]# runuser --login manageiq --command 'podman --root=/var/www/miq/vmdb/data/containers/storage images'
Error: configure storage: chown /var/www/miq/vmdb/data/containers/storage/overlay/l: operation not permitted
```

Permissions in the referenced folder:
```
[root@ljlab-ocp4aiops-ia-ic l]# ls -la /var/www/miq/vmdb/data/containers/storage/overlay/l
total 4
drwxr-sr-x. 2 root     root      108 Sep  6 03:59 .
drwx--S---. 6 manageiq manageiq 4096 Sep  6 08:28 ..
lrwxrwxrwx. 1 manageiq manageiq   72 Sep  4 17:08 QFEMEK4NE336HGLBPXRDGQ5HXY -> ../10a7e56d43ec054e2a2a41d44ddd6191d0b6b31963092fdce289a25130779c11/diff
lrwxrwxrwx. 1 manageiq manageiq   72 Sep  4 17:08 V6KC4MFFJKDKHNMVIZC4IBIOHH -> ../fa7ebf834ac0ab4b5502a285c0c111c627b7521b89d6b1d35ed0cb850f2fd58f/diff
lrwxrwxrwx. 1 manageiq manageiq   72 Sep  4 17:08 Y7KKSQHXHBTOARSYFHODZ2FAV3 -> ../9110f7b5208f035f4d4f99b5169338169e1df9bb2519d1b047f50f54430bacc2/diff
```

It does not help even if enable lingering with: `loginctl enable-linger 988` as suggested in the journal error:

```
[root@ljlab-ocp4aiops-ia-ic ~]# ls /var/lib/systemd/linger
manageiq
```

# Environment
ManageIQ version: IA vmware based appliance 4.6.1

Gem env:
```
[root@ljlab-ocp4aiops-ia-ic l]# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.27
  - RUBY VERSION: 3.1.5 (2024-04-23 patchlevel 252) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/IBM/infrastructure-management-gemset
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /opt/IBM/infrastructure-management-gemset/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /opt/IBM/infrastructure-management-gemset
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--install-dir=/usr/local/share/gems --bindir /usr/local/bin"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /root/.local/bin
     - /root/bin
     - /opt/IBM/infrastructure-management-gemset/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
```

**Comment by Fryguy** [comment] 2024-09-09 15:03
cc @bdunne - I think we've seen these similar issues elsewhere.

**Comment by agrare** [comment] 2024-09-09 15:20
I've seen this issue if the user accidentally runs a podman command as e.g. root then manageiq can't chown it.

```
ls -la /var/www/miq/vmdb/data/containers/storage/overlay/l
total 4
drwxr-sr-x. 2 root     root      108 Sep  6 03:59 .
```

This looks like the directory is indeed owned by `root` and not `manageiq`

**Comment by Fryguy** [comment] 2024-09-09 15:57
In this case @borazem ran the command as manageiq, or do you mean that if anything was run by root at least once then this happens?

Separately I recall we needed to set some environment variable XDG_USER something...not sure if that's the same issue/fix or not.

**Comment by agrare** [comment] 2024-09-09 16:09
> or do you mean that if anything was run by root at least once then this happens?

This, once it is owned by root only root can set it back to manageiq.  I don't think we set XDG_USER, we do have `--cgroups=split` which could resolve the warning but I don't think that is the root cause of the problem here.

@borazem you can try `chown -R manageiq\: /var/www/miq/vmdb/data/containers` but it is possible there are other directories that got bad permissions as well from whatever commands were run.

**Comment by borazem** [comment] 2024-09-09 17:01
Indeed I run once a podman command then I had to manually change ownership for few folders. but seems I missed that folder. Wonder what makes me run that command at that time.
Anyways, @agrare, the suggested with additional `chown -R manageiq\: /tmp/storage-run-988/containers/overlay` works.

**Comment by agrare** [comment] 2024-09-09 18:05
Thanks @borazem I'm going to close this let me know if you have any further issues

**Closed by agrare** 2024-09-09 18:05 UTC
Labels: bug
